
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/STARTER-jpa04
owner: ucsb-cs156-s25
repo_name: STARTER-jpa04
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-updateFrontendCI","number":2,"title":"Updating the Github Workflow Versions","url":"https://github.com/ucsb-cs156-s25/STARTER-jpa04/pull/2"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-updateStartingScript","number":1,"title":"Updating the Autoconfiguration Script","url":"https://github.com/ucsb-cs156-s25/STARTER-jpa04/pull/1"}]
